[package]
name = "recast-sys"
version = "0.1.0"
edition = "2021"

[features]
default = ["recast", "detour", "detour_crowd"]

detour = []
detour_crowd = ["detour"]
recast = []

[dependencies]
cxx = "1.0"

[build-dependencies]
cxx-build = "1.0"